#!/bin/bash

# Install Nginx
sudo apt update
sudo apt install nginx -y

# Configure redirection
sudo sed -i '/^}/ i \ \n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Test Nginx configuration
sudo nginx -t

# Restart Nginx to apply changes
sudo systemctl restart nginx
