#!/usr/bin/env bash

# Use awk to parse the Apache log file and print IP and HTTP status code
awk '{print $1, $9}' /path/to/apache_log_file |
# Use sort and uniq to count occurrences of IP and HTTP status code combinations
sort | uniq -c |
# Use awk to format the output as required and sort by occurrence number
awk '{print $1, $2, $3}' | sort -nr
